version: '3'
services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - 37017:27017
    command: mongod
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6370:6379
    command: redis-server