[ { id: 12,
  book_name: 'Harry Potter - A History of Magic',
  author_name: 'British Library',
  price: 1379.78,
  is_recommended: false },
{ id: 10,
  book_name: 'The Hate U Give',
  author_name: 'Angie Thomas',
  price: 319.16,
  is_recommended: false },
{ id: 7,
  book_name: 'Vegan 100',
  author_name: 'Gaz Oakley',
  price: 897.96,
  is_recommended: false },
{ id: 5,
  book_name: 'An American Princess: The Many Lives of Allene Tew',
  author_name: 'Annejet van der Zijl, Michele Hutchison',
  price: 149,
  is_recommended: false },
{ id: 3,
  book_name: 'Giraffes Can\'t Dance',
  author_name: 'Giles Andreae, Guy Parker-Rees',
  price: 200.5,
  is_recommended: false },
{ id: 2,
  book_name: 'When Never Comes',
  author_name: 'Barbara Davis',
  price: 179,
  is_recommended: false },
{ id: 1,
  book_name: 'Before We Were Yours: A Novel',
  author_name: 'Lisa Wingate',
  price: 340,
  is_recommended: false },
{ id: 4,
  book_name: 'The Great Alone: A Novel Kristin Hannah',
  author_name: 'Kristin Hannah',
  price: 495,
  is_recommended: false },
{ id: 6,
  book_name: 'Medical Medium Life-Changing Foods',
  author_name: 'Anthony William',
  price: 929.7,
  is_recommended: true },
{ id: 8,
  book_name: 'Have You Filled A Bucket Today?',
  author_name: 'Carol McCloud',
  price: 290.06,
  is_recommended: true },
{ id: 9,
  book_name: 'The Very Hungry Caterpillar',
  author_name: 'Eric Carle',
  price: 208.51,
  is_recommended: false },
{ id: 11,
  book_name: 'The Alice Network',
  author_name: 'Kate Quinn',
  price: 393.22,
  is_recommended: true } ];